# -*- coding: utf-8 -*-
"""1 Armonización de variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_vZEkVdpfHMg5rePeRKE4q6Hn0-PfRez

# **Configuración inicial**

## **Conección a Drive**
"""

!pip install pyreadstat

from google.colab import drive
drive.mount('/content/drive')

"""##**Rutas de guardado**"""

import os

# --- 1. CONFIGURACIÓN DE RUTAS ---
path_origen = "/content/drive/MyDrive/Observatorio/Bases/ENEMDU/Originales/Diciembres"
path_guardado = "/content/drive/MyDrive/Observatorio/Bases_limpias"

print("🧪 --- INICIANDO DIAGNÓSTICO DE RUTAS ---")

# A. Verificar Carpeta de Origen
if os.path.exists(path_origen):
    print(f"✅ Conexión con ORIGEN exitosa.")
    # Listar las subcarpetas para ver si coinciden con los rangos (90-99, 00-06, etc.)
    subcarpetas = [f for f in os.listdir(path_origen) if os.path.isdir(os.path.join(path_origen, f))]
    print(f"📂 Subcarpetas encontradas: {subcarpetas}")
else:
    print(f"❌ ERROR: No veo la ruta de ORIGEN. Revisa si el Drive está montado.")

# B. Verificar Carpeta de Guardado
if not os.path.exists(path_guardado):
    print(f"⚠️ La carpeta de GUARDADO no existe. Se creará automáticamente al procesar.")
else:
    print(f"✅ Carpeta de GUARDADO lista.")

# C. Muestreo de Archivos (El test real)
# Vamos a intentar ver un archivo de cada década para confirmar los nombres
test_años = [1995, 2005, 2015, 2024]

print("\n🔍 --- MUESTREO DE ARCHIVOS ---")
for anio in test_años:
    # Lógica de carpetas que planteamos
    if 1990 <= anio <= 1999: sub = "1990-1999"
    elif 2000 <= anio <= 2006: sub = "2000-2006"
    elif 2007 <= anio <= 2017: sub = "2007-2017"
    else: sub = os.path.join("2018-presente", "Trimestrales")

    folder_path = os.path.join(path_origen, sub)

    if os.path.exists(folder_path):
        archivos_en_folder = os.listdir(folder_path)
        # Buscamos algo que se parezca al año (ej: '95', '1995', '05')
        match = [f for f in archivos_en_folder if str(anio)[-2:] in f or str(anio) in f]
        if match:
            print(f"✅ Año {anio}: Encontrado como '{match[0]}' en la subcarpeta '{sub}'")
        else:
            print(f"❓ Año {anio}: La carpeta existe, pero no veo el archivo. Archivos ahí: {archivos_en_folder[:3]}...")
    else:
        print(f"❌ Año {anio}: No encuentro la subcarpeta '{sub}'")

import os

# Usamos la ruta que definimos antes
path_guardado = "/content/drive/MyDrive/Observatorio/Bases_limpias"
test_file = os.path.join(path_guardado, "test_permisos.txt")

print(f"📝 Intentando escribir en: {path_guardado}...")

try:
    # 1. Intentar crear un archivo
    with open(test_file, "w") as f:
        f.write("Test de permisos exitoso.")

    # 2. Verificar que se creó
    if os.path.exists(test_file):
        print("✅ TEST DE ESCRITURA EXITOSO: El script puede guardar archivos aquí.")
        # 3. Limpiar (borrar el archivo de test)
        os.remove(test_file)
        print("🧹 Archivo de prueba eliminado correctamente.")
    else:
        print("❌ ERROR: El archivo no se creó. Revisa los permisos de la carpeta.")

except Exception as e:
    print(f"❌ ERROR CRÍTICO DE ESCRITURA: {e}")
    print("\n💡 Tip: Asegúrate de que la carpeta 'Bases_limpias' no sea de 'Solo Lectura' o que tengas espacio en Drive.")

"""#**Mapeo de variables**"""

import pandas as pd
import pyreadstat
import os

# --- 1. CONFIGURACIÓN DE RUTAS ---
path_origen = "/content/drive/MyDrive/Observatorio/Bases/ENEMDU/Originales/Diciembres"
path_guardado = "/content/drive/MyDrive/Observatorio/Bases_limpias"
ruta_excel_mapa = os.path.join(path_guardado, "Mapa_Maestro_1990_2024.xlsx")

# --- 2. DICCIONARIO DE BÚSQUEDA (Esquema + Revisor) ---
var_buscadas = {
    "Genero": ["sexo", "p02"], #Emi
    "Edad": ["edad", "p03"], #Wil
    "Educación": ["nivinst", "p10a", "p10b", "anoinst"], #Wil
    "Estado civil": ["p06", "p07", "civil", "pe13c"],
    "Provincia": ["ciudad", "prov"], #Wil
    "Informal-Afiliación": ["iess", "p05a", "p05b"], # Wilson
    "Etnia": ["p15", "pe14", "pe13"], #Emi
    "Rama-Actividad": ["rama", "rama1", "ciiu"], #Emi
    "Informal-Sector informal": ["peamsiu", "secemp", "SECEMP"], # Wilson
    "Trabajo-Semana-Pasada": ["p20", "trabajo"],
    "Ayuda-Hogar": ["p21", "actayuda"],
    "Establecimiento tiene RUC": ["p49","pe51", "pe49", "pe51"],
    "Horas-Semana-Anterior": ["p24", "hortrasa"],
    "Desea-Mas-Horas": ["p27", "hormas", "ratmeh1"],
    "Ingreso-Laboral": ["ingrl", "ing_lab", "p66", "p59", "p54a"] # p54a/p59 comunes en 90s
}

datos_finales = []

# --- 3. EJECUCIÓN DEL ESCÁNER ---
for anio in range(1990, 2025):
    # Lógica de subcarpetas según diagnóstico exitoso
    if 1990 <= anio <= 1999: sub = "1990-1999"
    elif 2000 <= anio <= 2006: sub = "2000-2006"
    elif 2007 <= anio <= 2017: sub = "2007-2017"
    else: sub = os.path.join("2018-presente", "Trimestrales")

    archivo_nombre = f"empleo{anio}.dta"
    ruta_full = os.path.join(path_origen, sub, archivo_nombre)

    if os.path.exists(ruta_full):
        print(f"🔬 Escaneando {anio}...", end=" ")
        try:
            # Solo metadatos para velocidad
            _, meta = pyreadstat.read_dta(ruta_full, metadataonly=True)
            cols_reales = meta.column_names

            for concepto, posibles in var_buscadas.items():
                # Buscamos coincidencias (case insensitive)
                matches = [c for c in cols_reales if c.lower() in [p.lower() for p in posibles]]

                for m in matches:
                    # Capturamos etiquetas de valor (Stata Labels)
                    dicc = meta.variable_value_labels.get(m, {})
                    etiquetas = " / ".join([f"{k}:{v}" for k, v in dicc.items()]) if dicc else "Sin Etiquetas (Continua)"

                    datos_finales.append({
                        "Año": anio,
                        "Concepto_Analisis": concepto,
                        "Variable_Original_DTA": m,
                        "Etiquetas_Diccionario": etiquetas[:1000] # Evitar celdas gigantes en Excel
                    })
            print("✅")
        except Exception as e:
            print(f"❌ Error: {e}")
    else:
        print(f"⚠️ Año {anio} NO encontrado en ruta.")

# --- 4. EXPORTACIÓN FINAL ---
if datos_finales:
    df_mapa = pd.DataFrame(datos_finales)
    df_mapa.to_excel(ruta_excel_mapa, index=False)
    print(f"\n🔥 ¡MAPA MAESTRO GENERADO! Ubicación: {ruta_excel_mapa}")
else:
    print("\n❌ No se recolectaron datos. Revisa la lógica de búsqueda.")

"""# **Armonización**

## **Informal-Afiliación**
Indica si está afiliado al *IESS*
"""

import pandas as pd

# 1. Definimos la ruta exacta donde se guardó el mapa
ruta_mapa = "/content/drive/MyDrive/Observatorio/Bases_limpias/Mapa_Maestro_1990_2024.xlsx"

# 2. Cargamos el Excel que generamos hace un momento
df_mapa = pd.read_excel(ruta_mapa)

# 3. Filtramos solo para la variable de interés: Informal-Afiliación
# Nota: Verifica si en tu diccionario usamos 'Afiliación-IESS' o 'Informal-Afiliación'
mapa_afiliacion = df_mapa[df_mapa['Concepto_Analisis'] == 'Informal-Afiliación'].sort_values('Año')

# 4. Desplegamos el resultado para auditar
with pd.option_context('display.max_rows', None, 'display.max_colwidth', 500):
    print("📋 AUDITORÍA DE VARIABLE: AFILIACIÓN AL IESS (1990-2024)")
    print("-" * 100)
    if not mapa_afiliacion.empty:
        print(mapa_afiliacion[['Año', 'Variable_Original_DTA', 'Etiquetas_Diccionario']])
    else:
        print("⚠️ No se encontraron registros. Revisa si el nombre del concepto es 'Afiliación-IESS' o 'Informal-Afiliación' en tu diccionario.")

import pandas as pd
import pyreadstat
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# --- 1. CONFIGURACIÓN DE RUTAS ---
path_base = "/content/drive/MyDrive/Observatorio/Bases/ENEMDU/Originales/Diciembres"
path_limpias = "/content/drive/MyDrive/Observatorio/Bases_limpias"
ruta_mapa = os.path.join(path_limpias, "Mapa_Maestro_1990_2024.xlsx")

df_mapa = pd.read_excel(ruta_mapa)

def regla_estricta_iess(row, columnas, anio):
    """
    REGLA PEDIDA: Solo IESS General (No Voluntario, No Campesino)
    1: IESS General
    0: Otros Seguros o Ninguno
    """
    if anio <= 2000:
        # En los 90s no se puede separar, asumimos el 'si' como base general
        cods_iess = [1]
    elif 2001 <= anio <= 2006:
        # Según tu auditoría: 2 es IESS General. (3 es Campesino -> va a 0)
        cods_iess = [2]
    else:
        # Según tu auditoría: 1 es IESS General. (2 es Voluntario, 3 es Campesino -> van a 0)
        cods_iess = [1]

    for col in columnas:
        val = row[col]
        if pd.isna(val): continue
        try:
            if int(float(val)) in cods_iess:
                return 1
        except:
            continue
    return 0

# --- 2. PROCESAMIENTO ---
lista_master = []

for anio in range(1990, 2025):
    # Usando los nombres de columna de tu auditoría visual
    info_anio = df_mapa[(df_mapa['Año'] == anio) & (df_mapa['Concepto_Analisis'] == 'Informal-Afiliación')]
    if info_anio.empty: continue

    columnas_dta = [c for c in info_anio['Variable_Original_DTA'].unique() if c.lower() in ['iess', 'p05a']]

    if 1990 <= anio <= 1999: sub = "1990-1999"
    elif 2000 <= anio <= 2006: sub = "2000-2006"
    elif 2007 <= anio <= 2017: sub = "2007-2017"
    else: sub = os.path.join("2018-presente", "Trimestrales")

    ruta_input = os.path.join(path_base, sub, f"empleo{anio}.dta")

    if os.path.exists(ruta_input):
        print(f"🔄 Procesando {anio} (Estricto)...", end=" ")

        # Leemos solo IESS General (usualmente p05a o iess)
        df_t, meta = pyreadstat.read_dta(ruta_input, usecols=columnas_dta)

        df_t['iess_estricto'] = df_t.apply(lambda x: regla_estricta_iess(x, columnas_dta, anio), axis=1)
        df_t['anio'] = anio
        df_t['id_persona'] = df_t.index

        # Guardado DTA individual
        ruta_out = os.path.join(path_limpias, "Temporales", f"afilia_estricta_{anio}.dta")
        os.makedirs(os.path.dirname(ruta_out), exist_ok=True)

        pyreadstat.write_dta(df_t[['anio', 'id_persona', 'iess_estricto']], ruta_out,
                             column_labels={'iess_estricto': 'Solo IESS General (1:Si, 0:No)'},
                             variable_value_labels={'iess_estricto': {1: "IESS General", 0: "Otros/No"}})

        lista_master.append(df_t[['anio', 'id_persona', 'iess_estricto']])
        print("✅")

# --- 3. MASTER Y GRÁFICO ---
df_master_final = pd.concat(lista_master, ignore_index=True)
ruta_master = os.path.join(path_limpias, "Master_Afiliacion_Estricta_90_24.dta")
pyreadstat.write_dta(df_master_final, ruta_master)

# Control de %
control = df_master_final.groupby('anio')['iess_estricto'].mean() * 100
}
plt.figure(figsize=(12, 5))
plt.plot(control.index, control, marker='o', color='darkred', label='% IESS General')
plt.title('Evolución de la Afiliación Estricta (IESS General) 1990-2024')
plt.ylabel('Porcentaje (%)')
plt.grid(True, alpha=0.3)
plt.ylim(0, max(control)+10)
plt.show()

print(f"\n🚀 Master estricto guardado en: {ruta_master}")

"""### **Opción 2 IESS**"""

import pandas as pd
import pyreadstat
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# --- 1. CONFIGURACIÓN DE RUTAS ---
path_base = "/content/drive/MyDrive/Observatorio/Bases/ENEMDU/Originales/Diciembres"
path_limpias = "/content/drive/MyDrive/Observatorio/Bases_limpias"
ruta_mapa = os.path.join(path_limpias, "Mapa_Maestro_1990_2024.xlsx")

# Cargar Mapa Maestro
df_mapa = pd.read_excel(ruta_mapa)

def regla_formalidad_opcion2(row, columnas, anio):
    """
    OPCIÓN 2: Formalidad Laboral Civil y Militar
    1: IESS General + ISSFA (Militares) + ISSPOL (Policías)
    0: Seguro Campesino, Voluntario, Privado, Ninguno o Otros.
    """
    if anio <= 2000:
        # En los 90s, el '1' (Sí) es nuestra única base de formalidad
        cods_formal = [1]
    elif 2001 <= anio <= 2006:
        # 2: IESS General, 4: ISSFA/ISSPOL. (3: Campesino va a 0)
        cods_formal = [2, 4]
    else:
        # 1: IESS General, 4: ISSFA/ISSPOL. (2: Voluntario, 3: Campesino van a 0)
        cods_formal = [1, 4]

    for col in columnas:
        val = row[col]
        if pd.isna(val): continue
        try:
            if int(float(val)) in cods_formal:
                return 1
        except:
            continue
    return 0

# --- 2. PROCESAMIENTO ---
lista_master_op2 = []

for anio in range(1990, 2025):
    # Filtro según tu Mapa Maestro
    info_anio = df_mapa[(df_mapa['Año'] == anio) & (df_mapa['Concepto_Analisis'] == 'Informal-Afiliación')]
    if info_anio.empty: continue

    # Variables de interés (p05a suele ser general, p05b suele ser el resto)
    columnas_dta = [c for c in info_anio['Variable_Original_DTA'].unique() if c.lower() in ['iess', 'p05a', 'p05b']]

    # Lógica de subcarpetas
    if 1990 <= anio <= 1999: sub = "1990-1999"
    elif 2000 <= anio <= 2006: sub = "2000-2006"
    elif 2007 <= anio <= 2017: sub = "2007-2017"
    else: sub = os.path.join("2018-presente", "Trimestrales")

    ruta_input = os.path.join(path_base, sub, f"empleo{anio}.dta")

    if os.path.exists(ruta_input):
        print(f"🔄 Procesando {anio} (Opción 2: IESS + Militares)...", end=" ")

        # Lectura
        df_t, meta = pyreadstat.read_dta(ruta_input, usecols=columnas_dta)

        # Aplicar regla
        df_t['formal_op2'] = df_t.apply(lambda x: regla_formalidad_opcion2(x, columnas_dta, anio), axis=1)
        df_t['anio'] = anio
        df_t['id_persona'] = df_t.index

        # Guardado individual solicitado
        ruta_out = os.path.join(path_limpias, "Temporales", f"afilia_op2_{anio}.dta")
        os.makedirs(os.path.dirname(ruta_out), exist_ok=True)

        pyreadstat.write_dta(df_t[['anio', 'id_persona', 'formal_op2']], ruta_out,
                             column_labels={'formal_op2': 'Formalidad IESS+Militares (1:Si, 0:No)'})

        lista_master_op2.append(df_t[['anio', 'id_persona', 'formal_op2']])
        print("✅")

# --- 3. CONSOLIDACIÓN Y RESULTADOS ---
df_master_op2 = pd.concat(lista_master_op2, ignore_index=True)
ruta_save = os.path.join(path_limpias, "Master_Afiliacion_Opcion2_90_24.dta")
pyreadstat.write_dta(df_master_op2, ruta_save)

# --- 4. TABLA DE RESULTADOS EN COLAB ---
tabla_res = pd.crosstab(df_master_op2['anio'], df_master_op2['formal_op2'], normalize='index') * 100
tabla_res.columns = ['% Informal/Otros (0)', '% Formal IESS+Mil (1)']

print("\n📊 TABLA DE CONTROL - OPCIÓN 2 (IESS GENERAL + ISSFA/ISSPOL)")
display(tabla_res.round(2))

# Gráfico rápido
plt.figure(figsize=(10, 4))
plt.plot(tabla_res.index, tabla_res['% Formal IESS+Mil (1)'], marker='o', color='navy')
plt.title('Tendencia de Formalidad Laboral (Opción 2)')
plt.grid(True, alpha=0.3)
plt.show()

print(f"\n🚀 Master Opción 2 guardado en: {ruta_save}")

"""## **Informal-Sector informal**"""

import pandas as pd

# 1. Ruta del mapa maestro
ruta_mapa = "/content/drive/MyDrive/Observatorio/Bases_limpias/Mapa_Maestro_1990_2024.xlsx"

# 2. Cargar el mapa
df_mapa = pd.read_excel(ruta_mapa)

# 3. Usamos el nombre exacto que detectamos en tu lista
concepto_buscado = 'Informal-Sector informal'
mapa_sector = df_mapa[df_mapa['Concepto_Analisis'] == concepto_buscado].sort_values('Año')

# 4. Desplegar con auditoría de etiquetas/diccionario
with pd.option_context('display.max_rows', None, 'display.max_colwidth', 500):
    print(f"📋 AUDITORÍA DE VARIABLE: {concepto_buscado} (1990-2024)")
    print("-" * 120)

    if not mapa_sector.empty:
        # Mostramos Año, la Variable original y las Etiquetas
        columnas_ver = ['Año', 'Variable_Original_DTA', 'Etiquetas_Diccionario']
        columnas_finales = [c for c in columnas_ver if c in mapa_sector.columns]

        print(mapa_sector[columnas_finales].to_string(index=False))
    else:
        print(f"⚠️ No se encontró el concepto '{concepto_buscado}'.")

import pandas as pd
import pyreadstat
import os

# --- 1. CONFIGURACIÓN ---
path_base = "/content/drive/MyDrive/Observatorio/Bases/ENEMDU/Originales/Diciembres"
path_limpias = "/content/drive/MyDrive/Observatorio/Bases_limpias"
ruta_mapa = os.path.join(path_limpias, "Mapa_Maestro_1990_2024.xlsx")
df_mapa = pd.read_excel(ruta_mapa)

def regla_sector_binario(row, columnas):
    """
    Regla universal basada en auditoría:
    1: Sector Informal (Código 2)
    0: Cualquier otro sector (Formal, Doméstico, Agrícola, No clasificado)
    """
    for col in columnas:
        val = row[col]
        if pd.isna(val): continue
        try:
            if int(float(val)) == 2:
                return 1
        except:
            continue
    return 0

# --- 2. PROCESAMIENTO ---
lista_sector = []

for anio in range(1990, 2025):
    info_anio = df_mapa[(df_mapa['Año'] == anio) &
                        (df_mapa['Concepto_Analisis'] == 'Informal-Sector informal')]

    if info_anio.empty: continue

    # Capturamos las variables detectadas (peamsiu, SECEMP, secemp)
    columnas_dta = [c for c in info_anio['Variable_Original_DTA'].unique()]

    # Lógica de carpetas
    if 1990 <= anio <= 1999: sub = "1990-1999"
    elif 2000 <= anio <= 2006: sub = "2000-2006"
    elif 2007 <= anio <= 2017: sub = "2007-2017"
    else: sub = os.path.join("2018-presente", "Trimestrales")

    ruta_input = os.path.join(path_base, sub, f"empleo{anio}.dta")

    if os.path.exists(ruta_input):
        print(f"🔄 Procesando Sector {anio}...", end=" ")
        df_t, _ = pyreadstat.read_dta(ruta_input, usecols=columnas_dta)

        df_t['sector_informal'] = df_t.apply(lambda x: regla_sector_binario(x, columnas_dta), axis=1)
        df_t['anio'] = anio
        df_t['id_persona'] = df_t.index

        lista_sector.append(df_t[['anio', 'id_persona', 'sector_informal']])
        print("✅")

# Consolidación
df_master_sector = pd.concat(lista_sector, ignore_index=True)
ruta_master_sec = os.path.join(path_limpias, "Master_Sector_Informal_90_24.dta")
pyreadstat.write_dta(df_master_sector, ruta_master_sec)
print(f"\n🚀 Master de Sector guardado en: {ruta_master_sec}")

import matplotlib.pyplot as plt

# 1. Tabla de control
tabla_sec = pd.crosstab(df_master_sector['anio'], df_master_sector['sector_informal'], normalize='index') * 100
tabla_sec.columns = ['% Resto (Formal/Domest/Agro)', '% Sector Informal (1)']

print("\n📊 RESULTADOS HISTÓRICOS: SECTOR INFORMAL")
display(tabla_sec.round(2))

# 2. Gráfico
plt.figure(figsize=(12, 5))
plt.plot(tabla_sec.index, tabla_sec['% Sector Informal (1)'],
         marker='s', color='#E67E22', linewidth=2, label='Tasa Sector Informal')

plt.title('Evolución del Sector Informal en Ecuador (1990-2024)', fontsize=14)
plt.ylabel('Porcentaje (%)')
plt.ylim(0, 100)
plt.grid(True, alpha=0.3)
plt.legend()
plt.show()

import matplotlib.pyplot as plt

# 1. Tabla de control
tabla_sec = pd.crosstab(df_master_sector['anio'], df_master_sector['sector_informal'], normalize='index') * 100
tabla_sec.columns = ['% Resto (Formal/Domest/Agro)', '% Sector Informal (1)']

print("\n📊 RESULTADOS HISTÓRICOS: SECTOR INFORMAL")
display(tabla_sec.round(2))

# 2. Gráfico
plt.figure(figsize=(12, 5))
plt.plot(tabla_sec.index, tabla_sec['% Sector Informal (1)'],
         marker='s', color='#E67E22', linewidth=2, label='Tasa Sector Informal')

plt.title('Evolución del Sector Informal en Ecuador (1990-2024)', fontsize=14)
plt.ylabel('Porcentaje (%)')
plt.ylim(0, 100)
plt.grid(True, alpha=0.3)
plt.legend()
plt.show()

"""### **Opcion 2 Informalidad**"""

import pandas as pd
import pyreadstat
import os
import numpy as np

# --- 1. CONFIGURACIÓN ---
path_base = "/content/drive/MyDrive/Observatorio/Bases/ENEMDU/Originales/Diciembres"
path_limpias = "/content/drive/MyDrive/Observatorio/Bases_limpias"
ruta_mapa = os.path.join(path_limpias, "Mapa_Maestro_1990_2024.xlsx")
df_mapa = pd.read_excel(ruta_mapa)

def regla_sector_detallado(row, columnas, anio):
    """
    Lógica de Clasificación Independiente (Armonizada 1990-2024)
    """
    for col in columnas:
        val = row[col]
        if pd.isna(val): continue
        v = int(float(val))

        # Categoría 1: Sector Formal (Empresas con RUC, Estado, Moderno)
        if v == 1:
            return "Sector Formal"

        # Categoría 2: Sector Informal (Independientes, Negocios de Hogar)
        elif v == 2:
            return "Sector Informal"

        # Categoría 3: Empleo Doméstico (Remunerado)
        elif v in [3, 4] and "doméstico" in str(row).lower():
            # Nota: En los 90s era 4, hoy es 3. La auditoría nos guía.
            return "Empleo Doméstico"

        # Categoría 4: Sector Agropecuario / No Remunerado (Específico 90s)
        elif anio < 2007 and v == 3:
            return "Sector Agropecuario"

        # Categoría 5: No Clasificados o Otros
        elif v in [4, 5]:
            return "Otros / No Clasificados"

    return "No clasificado"

# --- 2. PROCESAMIENTO ---
lista_master = []

for anio in range(1990, 2025):
    # Usamos el concepto exacto de tu auditoría
    info_anio = df_mapa[(df_mapa['Año'] == anio) &
                        (df_mapa['Concepto_Analisis'] == 'Informal-Sector informal')]

    if info_anio.empty: continue
    columnas_dta = [c for c in info_anio['Variable_Original_DTA'].unique()]

    # Selección de carpeta según época
    if 1990 <= anio <= 1999: sub = "1990-1999"
    elif 2000 <= anio <= 2006: sub = "2000-2006"
    elif 2007 <= anio <= 2017: sub = "2007-2017"
    else: sub = os.path.join("2018-presente", "Trimestrales")

    ruta_input = os.path.join(path_base, sub, f"empleo{anio}.dta")

    if os.path.exists(ruta_input):
        print(f"📊 Procesando Estructura {anio}...", end=" ")
        # Leemos la variable (peamsiu, secemp, etc)
        df_t, _ = pyreadstat.read_dta(ruta_input, usecols=columnas_dta)

        # Aplicamos la lógica multicategoría
        df_t['categoria_sector'] = df_t.apply(lambda x: regla_sector_detallado(x, columnas_dta, anio), axis=1)
        df_t['anio'] = anio
        df_t['id_persona'] = df_t.index

        lista_master.append(df_t[['anio', 'id_persona', 'categoria_sector']])
        print("✅")

# Guardado del Master Multicategoría
df_master_final = pd.concat(lista_master, ignore_index=True)
ruta_save = os.path.join(path_limpias, "Master_Estructura_Sector_90_24.dta")
pyreadstat.write_dta(df_master_final, ruta_save)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# --- 1. CARGA DE DATOS ---
path_limpias = "/content/drive/MyDrive/Observatorio/Bases_limpias"
ruta_master = os.path.join(path_limpias, "Master_Estructura_Sector_90_24.dta")

df_master = pd.read_stata(ruta_master)

# --- 2. GENERACIÓN DE TABLA DE CONTROL ---
# Creamos una tabla de proporciones (frecuencia relativa) por año
tabla_control = pd.crosstab(df_master['anio'], df_master['categoria_sector'], normalize='index') * 100

print("📊 TABLA DE CONTROL: ESTRUCTURA DEL MERCADO LABORAL (1990-2024)")
print("-" * 80)
display(tabla_control.round(2))

# --- 3. VISUALIZACIÓN DE COMPOSICIÓN (Gráfico de Áreas Apiladas) ---
plt.figure(figsize=(14, 7))

# Definimos un orden lógico para las capas del gráfico
# Abajo lo más estable (Formal), arriba lo más volátil o residual
categorias_orden = [
    "Sector Formal",
    "Sector Informal",
    "Sector Agropecuario",
    "Empleo Doméstico",
    "Otros / No Clasificados"
]

# Filtramos solo las categorías que realmente existan en los datos para evitar errores
capas = [c for c in categorias_orden if c in tabla_control.columns]

# Paleta de colores profesional
colores = ["#2E86C1", "#E67E22", "#27AE60", "#F1C40F", "#95A5A6"]

# Crear el gráfico de áreas
plt.stackplot(tabla_control.index,
              [tabla_control[c] for c in capas],
              labels=capas,
              colors=colores,
              alpha=0.85)

# Personalización estética
plt.title('Evolución de la Estructura Productiva en Ecuador (1990-2024)', fontsize=16, fontweight='bold')
plt.ylabel('Participación en el Mercado Laboral (%)', fontsize=12)
plt.xlabel('Año', fontsize=12)
plt.xlim(1990, 2024)
plt.ylim(0, 100)
plt.legend(loc='upper center', bbox_to_anchor=(0.5, -0.1), ncol=3, frameon=False)
plt.grid(axis='y', linestyle='--', alpha=0.5)

# Añadir línea vertical en 2007 (Cambio Metodológico Importante)
plt.axvline(x=2007, color='black', linestyle=':', alpha=0.7)
plt.text(2007.5, 95, 'Cambio Metodología (INEC)', fontsize=10, fontstyle='italic')

plt.tight_layout()
plt.show()

"""## **Edad**"""

import pandas as pd
import os

# --- 1. CONFIGURACIÓN ---
ruta_mapa = "/content/drive/MyDrive/Observatorio/Bases_limpias/Mapa_Maestro_1990_2024.xlsx"
df_mapa = pd.read_excel(ruta_mapa)

# --- 2. FILTRADO POR CONCEPTO ---
# Filtramos exactamente por el concepto de tu lista: 'Edad'
mapa_edad = df_mapa[df_mapa['Concepto_Analisis'] == 'Edad'].sort_values('Año')

# --- 3. DESPLIEGUE DE AUDITORÍA ---
with pd.option_context('display.max_rows', None, 'display.max_colwidth', 500):
    print("📋 AUDITORÍA DE VARIABLE: EDAD (1990-2024)")
    print("-" * 100)

    if not mapa_edad.empty:
        # Mostramos Año, la Variable original y si hay alguna nota en el diccionario
        columnas_ver = ['Año', 'Variable_Original_DTA', 'Etiquetas_Diccionario']
        columnas_finales = [c for c in columnas_ver if c in mapa_edad.columns]

        print(mapa_edad[columnas_finales].to_string(index=False))

        # Conteo de variables distintas para ver la consistencia
        print("\n📌 Variables detectadas para Edad:", mapa_edad['Variable_Original_DTA'].unique())
    else:
        print("⚠️ No se encontró el concepto 'Edad'.")
        print("Conceptos disponibles para verificar nombre:")
        print(df_mapa['Concepto_Analisis'].unique())

import pandas as pd
import pyreadstat
import os
import numpy as np

# --- 1. CONFIGURACIÓN ---
path_base = "/content/drive/MyDrive/Observatorio/Bases/ENEMDU/Originales/Diciembres"
path_limpias = "/content/drive/MyDrive/Observatorio/Bases_limpias"
ruta_mapa = os.path.join(path_limpias, "Mapa_Maestro_1990_2024.xlsx")
df_mapa = pd.read_excel(ruta_mapa)

def categorizar_edad_ecuador(e):
    if pd.isna(e) or e == 99 or e < 0:
        return "N/D"
    if e < 15:
        return "1. Menores (<15)"
    if 15 <= e <= 29:
        # Rango clave para políticas de empleo juvenil en Ecuador
        return "2. Jóvenes (15-29)"
    if 30 <= e <= 64:
        return "3. Adultos (30-64)"
    return "4. Adultos Mayores (65+)"

# --- 2. PROCESAMIENTO ---
lista_edad = []

for anio in range(1990, 2025):
    # Filtramos la variable específica según el mapa
    info_anio = df_mapa[(df_mapa['Año'] == anio) & (df_mapa['Concepto_Analisis'] == 'Edad')]
    if info_anio.empty: continue

    columna_dta = info_anio['Variable_Original_DTA'].values[0]

    # Lógica de subcarpetas (estándar que ya manejamos)
    if 1990 <= anio <= 1999: sub = "1990-1999"
    elif 2000 <= anio <= 2006: sub = "2000-2006"
    elif 2007 <= anio <= 2017: sub = "2007-2017"
    else: sub = os.path.join("2018-presente", "Trimestrales")

    ruta_input = os.path.join(path_base, sub, f"empleo{anio}.dta")

    if os.path.exists(ruta_input):
        print(f"🎂 Procesando Edad {anio} ({columna_dta})...", end=" ")
        df_t, _ = pyreadstat.read_dta(ruta_input, usecols=[columna_dta])

        # 1. Limpieza y conversión
        df_t['edad_num'] = pd.to_numeric(df_t[columna_dta], errors='coerce')

        # 2. Aplicar categorización
        df_t['grupo_etario'] = df_t['edad_num'].apply(categorizar_edad_ecuador)

        # 3. Identificador de PET (Población en Edad de Trabajar)
        # Es vital para que luego solo analices informalidad en este grupo
        df_t['es_pet'] = (df_t['edad_num'] >= 15) & (df_t['edad_num'] < 99)

        df_t['anio'] = anio
        df_t['id_persona'] = df_t.index

        lista_edad.append(df_t[['anio', 'id_persona', 'edad_num', 'grupo_etario', 'es_pet']])
        print("✅")

# Consolidación
df_master_edad = pd.concat(lista_edad, ignore_index=True)
ruta_save = os.path.join(path_limpias, "Master_Edad_90_24.dta")
pyreadstat.write_dta(df_master_edad, ruta_save)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# --- 1. CARGA DE DATOS ---
path_limpias = "/content/drive/MyDrive/Observatorio/Bases_limpias"
ruta_master_edad = os.path.join(path_limpias, "Master_Edad_90_24.dta")

df_edad = pd.read_stata(ruta_master_edad)

# --- 2. TABLA DE CONTROL (Distribución Porcentual por Año) ---
# Filtramos N/D para que la distribución sea sobre datos válidos
tabla_edad = pd.crosstab(df_edad['anio'], df_edad['grupo_etario'], normalize='index') * 100

print("📊 DISTRIBUCIÓN POR GRUPOS DE EDAD (1990-2024)")
print("-" * 80)
display(tabla_edad.round(2))

# --- 3. GRÁFICO DE ÁREAS APILADAS (Transición Demográfica) ---
plt.figure(figsize=(14, 7))

# Orden lógico: Menores abajo, Adultos mayores arriba
orden_etario = [
    "1. Menores (<15)",
    "2. Jóvenes (15-29)",
    "3. Adultos (30-64)",
    "4. Adultos Mayores (65+)"
]

# Paleta de colores (de tonos cálidos a fríos para marcar madurez)
colores_edad = ["#FADBD8", "#F1948A", "#C0392B", "#641E16"]

plt.stackplot(tabla_edad.index,
              [tabla_edad[c] for c in orden_etario if c in tabla_edad.columns],
              labels=orden_etario,
              colors=colores_edad,
              alpha=0.8)

# Personalización
plt.title('Transición de la Estructura Etaria en Ecuador (1990-2024)', fontsize=16, fontweight='bold')
plt.ylabel('Participación Poblacional (%)', fontsize=12)
plt.xlabel('Año', fontsize=12)
plt.legend(loc='upper center', bbox_to_anchor=(0.5, -0.1), ncol=4, frameon=False)
plt.grid(axis='y', linestyle='--', alpha=0.3)
plt.xlim(1990, 2024)
plt.ylim(0, 100)

plt.tight_layout()
plt.show()

# --- 4. BONUS: CÁLCULO DE LA PET MEDIA ---
pet_promedio = df_edad[df_edad['es_pet'] == True].groupby('anio')['edad_num'].mean()
print("\n📈 TENDENCIA: Edad promedio de la Población en Edad de Trabajar (PET)")
print(pet_promedio.tail(10).round(2))

"""##**Provincia**"""

import pandas as pd
import os

# 1. Cargar el Mapa Maestro
ruta_mapa = "/content/drive/MyDrive/Observatorio/Bases_limpias/Mapa_Maestro_1990_2024.xlsx"
df_mapa = pd.read_excel(ruta_mapa)

# 2. El Filtro Maestro (4 columnas + Concepto Provincia)
# Buscamos el concepto y seleccionamos las columnas exactas que analizamos
columnas_interes = ['Año', 'Concepto_Analisis', 'Variable_Original_DTA', 'Etiquetas_Diccionario']

df_prov_audit = df_mapa[df_mapa['Concepto_Analisis'] == 'Provincia'][columnas_interes].sort_values('Año')

# 3. Mostrar el resultado con formato limpio
print("🗺️ REPORTE TÉCNICO: MAPEO DE PROVINCIAS 1990-2024")
print("-" * 110)
with pd.option_context('display.max_rows', None, 'display.max_colwidth', 80):
    print(df_prov_audit.to_string(index=False))

# 4. Análisis de consistencia para el programador
print("-" * 110)
vars_detectadas = df_prov_audit['Variable_Original_DTA'].unique()
print(f"📌 Variables originales detectadas: {vars_detectadas}")

import pandas as pd
import pyreadstat
import os
import numpy as np

# --- 1. CONFIGURACIÓN ---
path_base = "/content/drive/MyDrive/Observatorio/Bases/ENEMDU/Originales/Diciembres"
path_limpias = "/content/drive/MyDrive/Observatorio/Bases_limpias"
ruta_mapa = os.path.join(path_limpias, "Mapa_Maestro_1990_2024.xlsx")
df_mapa = pd.read_excel(ruta_mapa)

def extraer_provincia_wil(row, columna_usada):
    try:
        val = str(row[columna_usada]).strip().replace('.0', '')
        if val == 'nan' or val == '': return "N/D"

        # Lógica Wil: Estandarizar a 6 dígitos para rebanar los 2 primeros
        if len(val) >= 5:
            val_padd = val.zfill(6)
            prov = val_padd[:2]
        else:
            # Para códigos directos (1, 2, 9, 17...)
            prov = val.zfill(2)

        # Validación DPA Ecuador (01-24 + 90)
        if prov.isdigit() and (1 <= int(prov) <= 24 or int(prov) == 90):
            return prov
        return "N/D"
    except:
        return "N/D"

# --- 2. PROCESAMIENTO ---
datos_prov_acumulados = []

for anio in range(1990, 2025):
    # Filtrar mapa por el concepto 'Provincia'
    info_anio = df_mapa[(df_mapa['Año'] == anio) & (df_mapa['Concepto_Analisis'] == 'Provincia')]
    if info_anio.empty: continue

    # Detectar variable a usar (prioridad 'prov' sobre 'ciudad' según tu reporte)
    vars_en_excel = info_anio['Variable_Original_DTA'].values
    columna_a_usar = 'prov' if 'prov' in vars_en_excel else 'ciudad'

    # Manejo de rutas por carpetas
    if 1990 <= anio <= 1999: sub = "1990-1999"
    elif 2000 <= anio <= 2006: sub = "2000-2006"
    elif 2007 <= anio <= 2017: sub = "2007-2017"
    else: sub = os.path.join("2018-presente", "Trimestrales")

    ruta_input = os.path.join(path_base, sub, f"empleo{anio}.dta")

    if os.path.exists(ruta_input):
        print(f"📍 {anio} OK ({columna_a_usar})", end=" | ")
        # Leemos solo la columna que necesitamos
        try:
            df_t, _ = pyreadstat.read_dta(ruta_input, usecols=[columna_a_usar])

            df_t['provincia_cod'] = df_t.apply(lambda x: extraer_provincia_wil(x, columna_a_usar), axis=1)
            df_t['anio'] = anio
            df_t['id_persona'] = df_t.index

            datos_prov_acumulados.append(df_t[['anio', 'id_persona', 'provincia_cod']])
        except Exception as e:
            print(f"⚠️ Error en {anio}: {e}")
    else:
        print(f"❌ {anio} Faltante")

# Unión final
df_prov_master = pd.concat(datos_prov_acumulados, ignore_index=True)
ruta_save = os.path.join(path_limpias, "Master_Provincia_90_24.dta")
pyreadstat.write_dta(df_prov_master, ruta_save)

print(f"\n\n✅ PROCESO TERMINADO. Registros: {len(df_prov_master)}")

# Tabla de control: ¿Cómo se ven los códigos por año?
control_prov = pd.crosstab(df_prov_master['anio'], df_prov_master['provincia_cod'])

print("📋 TABLA DE CONTROL: CÓDIGOS DE PROVINCIA POR AÑO")
print("-" * 80)
# Mostramos una muestra de los códigos para verificar
display(control_prov[['01', '09', '17', '23', '24']].tail(15))

# Verificación de "N/D"
total_nd = df_prov_master[df_prov_master['provincia_cod'] == 'N/D'].shape[0]
print(f"\n❓ Total de registros con N/D: {total_nd} ({round(total_nd/len(df_prov_master)*100, 2)}%)")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# --- 1. CONFIGURACIÓN Y MAPEO ---
# Cargamos el Master de Provincias que generamos
path_limpias = "/content/drive/MyDrive/Observatorio/Bases_limpias"
ruta_master_prov = os.path.join(path_limpias, "Master_Provincia_90_24.dta")
df_prov = pd.read_stata(ruta_master_prov)

# Diccionario Maestro para etiquetas legibles (Opcional, pero muy recomendado)
DICCIONARIO_NOMBRES = {
    '01': 'Azuay', '02': 'Bolívar', '03': 'Cañar', '04': 'Carchi', '05': 'Cotopaxi',
    '06': 'Chimborazo', '07': 'El Oro', '08': 'Esmeraldas', '09': 'Guayas', '10': 'Imbabura',
    '11': 'Loja', '12': 'Los Ríos', '13': 'Manabí', '14': 'Morona S.', '15': 'Napo',
    '16': 'Pastaza', '17': 'Pichincha', '18': 'Tungurahua', '19': 'Zamora C.',
    '20': 'Galápagos', '21': 'Sucumbíos', '22': 'Orellana', '23': 'Sto. Domingo', '24': 'Sta. Elena',
    '90': 'Zonas N.D.'
}

# --- 2. PREPARACIÓN DE DATOS (HEATMAP) ---
# Creamos la tabla de contingencia (Año vs Código de Provincia)
tabla_heat = pd.crosstab(df_prov['anio'], df_prov['provincia_cod'], normalize='index') * 100

# Reordenamos las provincias para que sigan el orden lógico DPA (01 a 24)
columnas_ordenadas = sorted([c for c in tabla_heat.columns if c.isdigit()])
tabla_heat = tabla_heat[columnas_ordenadas]

# Renombramos las columnas usando el diccionario para que el gráfico tenga nombres
tabla_heat.columns = [DICCIONARIO_NOMBRES.get(c, c) for c in tabla_heat.columns]

# --- 3. GENERACIÓN DEL GRÁFICO (HEATMAP) ---
plt.figure(figsize=(16, 10))

# Usamos la paleta "YlGnBu" (de amarillo a azul oscuro) para marcar la densidad
sns.heatmap(tabla_heat.T, # Transponemos para que las provs queden en el eje Y
            cmap="YlGnBu",
            linewidths=.2,
            cbar_kws={'label': 'Participación en la Muestra (%)'},
            xticklabels=2, # Mostramos el año cada 2 para que no se amontonen
            )

# Personalización
plt.title('Mapa de Calor de Consistencia Provincial: Participación Relativa (1990-2024)', fontsize=16, fontweight='bold')
plt.ylabel('Provincia (Código DPA)', fontsize=12)
plt.xlabel('Año de la Encuesta', fontsize=12)

# Ajuste de las etiquetas del eje Y para que no se corten
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# --- 4. BONUS: CÁLCULO DE N/D (CONFIRMACIÓN) ---
print("-" * 50)
print("📌 Verificación final de registros N/D:")
total_registros = len(df_prov)
total_nd = df_prov[df_prov['provincia_cod'] == 'N/D'].shape[0]
print(f"Total registros: {total_registros}")
print(f"Registros N/D: {total_nd} (0.0%)")

"""## **Nivel educativo**"""

import pandas as pd

# 1. Cargar el mapa
ruta_mapa = "/content/drive/MyDrive/Observatorio/Bases_limpias/Mapa_Maestro_1990_2024.xlsx"
df_mapa = pd.read_excel(ruta_mapa)

# 2. Filtrar por el concepto relacionado con educación
# Nota: Revisa si en tu Excel el concepto es 'Nivel Instrucción', 'Educación' o 'Instrucción'
filtro_edu = df_mapa['Concepto_Analisis'].str.contains('Instrucción|Educación|Nivel', case=False, na=False)
df_edu_audit = df_mapa[filtro_edu][['Año', 'Concepto_Analisis', 'Variable_Original_DTA', 'Etiquetas_Diccionario']].sort_values('Año')

# 3. Desplegar auditoría
print("🎓 AUDITORÍA DE VARIABLE: NIVEL EDUCATIVO (1990-2024)")
print("-" * 110)
with pd.option_context('display.max_rows', None, 'display.max_colwidth', 100):
    if not df_edu_audit.empty:
        print(df_edu_audit.to_string(index=False))
    else:
        print("⚠️ No se encontró el concepto. Revisa los nombres en la columna 'Concepto_Analisis'.")

import pandas as pd
import pyreadstat
import os

# --- 1. FUNCIÓN DE ARMONIZACIÓN (La "Traducción") ---
def armonizar_educacion_wil(row, col, anio):
    try:
        if col not in row or pd.isna(row[col]): return "N/D"
        v = int(float(row[col]))

        # Época A: 1990 - 2000 (Escala de 5 niveles)
        if anio <= 2000:
            mapping = {1: "1. Sin Instrucción", 2: "1. Sin Instrucción",
                       3: "2. Primaria", 4: "3. Secundaria", 5: "4. Superior"}

        # Época B: 2001 - 2002 (Escala de 8 niveles)
        elif 2001 <= anio <= 2002:
            mapping = {1: "1. Sin Instrucción", 2: "1. Sin Instrucción", 3: "1. Sin Instrucción",
                       4: "2. Primaria", 5: "3. Secundaria", 6: "4. Superior", 7: "4. Superior",
                       8: "5. Postgrado"}

        # Época C: 2003 - 2024 (Escala de 10 niveles - Reforma Educativa)
        else:
            mapping = {1: "1. Sin Instrucción", 2: "1. Sin Instrucción", 3: "1. Sin Instrucción",
                       4: "2. Primaria", 5: "2. Primaria", 6: "3. Secundaria", 7: "3. Secundaria",
                       8: "4. Superior", 9: "4. Superior", 10: "5. Postgrado"}

        return mapping.get(v, "N/D")
    except:
        return "N/D"

# --- 2. LOOP DE INTEGRACIÓN ---
datos_edu_acumulados = []

for anio in range(1990, 2025):
    info_anio = df_mapa[(df_mapa['Año'] == anio) & (df_mapa['Concepto_Analisis'] == 'Educación')]
    if info_anio.empty: continue

    # Detectamos cuál variable usar según tu reporte (p10a o nivinst)
    columna_a_usar = info_anio['Variable_Original_DTA'].iloc[0]
    # (Si hay dos variables como p10a y p10b, tomamos la categórica p10a)

    sub = "1990-1999" if anio <= 1999 else "2000-2006" if anio <= 2006 else "2007-2017" if anio <= 2017 else "2018-presente/Trimestrales"
    ruta = os.path.join(path_base, sub, f"empleo{anio}.dta")

    if os.path.exists(ruta):
        # Leemos solo la columna de educación
        df_t, _ = pyreadstat.read_dta(ruta, usecols=[columna_a_usar])

        # Aplicamos la armonización
        df_t['nivel_educativo'] = df_t.apply(lambda x: armonizar_educacion_wil(x, columna_a_usar, anio), axis=1)
        df_t['anio'] = anio
        df_t['id_persona'] = df_t.index

        datos_edu_acumulados.append(df_t[['anio', 'id_persona', 'nivel_educativo']])
        print(f"🎓 {anio} OK ({columna_a_usar})", end=" | ")

# Unificar y Guardar
df_edu_final = pd.concat(datos_edu_acumulados, ignore_index=True)
df_edu_final.to_stata(os.path.join(path_limpias, "Master_Educacion_90_24.dta"), write_index=False)

# Verificamos la evolución de la educación en Ecuador
tabla_edu = pd.crosstab(df_edu_final['anio'], df_edu_final['nivel_educativo'], normalize='index') * 100

print("📈 EVOLUCIÓN DEL NIVEL EDUCATIVO (1990-2024)")
print("-" * 80)
display(tabla_edu.round(2))

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Preparar los datos para la gráfica
# Usamos la tabla_edu que generamos en el bloque anterior
plot_data = tabla_edu.copy()

# 2. Configurar el estilo
plt.figure(figsize=(14, 8))
sns.set_style("whitegrid")

# 3. Crear el gráfico de áreas apiladas
paleta = sns.color_palette("viridis", n_colors=len(plot_data.columns))

plt.stackplot(plot_data.index,
              [plot_data[col] for col in plot_data.columns],
              labels=plot_data.columns,
              colors=paleta,
              alpha=0.8)

# 4. Personalización estética
plt.title('Evolución de la Estructura Educativa en Ecuador (1990-2024)', fontsize=16, fontweight='bold')
plt.ylabel('Distribución Porcentual (%)', fontsize=12)
plt.xlabel('Año', fontsize=12)
plt.legend(loc='upper left', bbox_to_anchor=(1, 1), title="Nivel Instrucción")
plt.xlim(1990, 2024)
plt.ylim(0, 100)

# Añadir una nota sobre la reforma educativa
plt.annotate('Reforma Educativa\n(10 niveles)', xy=(2003, 50), xytext=(1995, 20),
             arrowprops=dict(facecolor='black', shrink=0.05, width=1))

plt.tight_layout()
plt.show()

"""### **Opcion 2 Nivel educativo**"""

import pandas as pd

# 1. Cargar el mapa maestro actualizado
ruta_mapa = "/content/drive/MyDrive/Observatorio/Bases_limpias/Mapa_Maestro_1990_2024.xlsx"
df_mapa = pd.read_excel(ruta_mapa)

# 2. Filtrar por los conceptos de Nivel y Años de estudio
# Buscamos ambos para ver cómo se emparejan por año
conceptos_edu = ['Educación', 'Nivel Instrucción', 'Años de estudio', 'Grado aprobado']
filtro_edu_completo = df_mapa['Concepto_Analisis'].str.contains('|'.join(conceptos_edu), case=False, na=False)

df_edu_duo = df_mapa[filtro_edu_completo][['Año', 'Concepto_Analisis', 'Variable_Original_DTA', 'Etiquetas_Diccionario']].sort_values(['Año', 'Concepto_Analisis'])

# 3. Mostrar reporte enfocado en la transición
print("📊 AUDITORÍA DE CONSISTENCIA: NIVEL vs. AÑOS (1990-2024)")
print("-" * 120)
with pd.option_context('display.max_rows', None, 'display.max_colwidth', 80):
    print(df_edu_duo.to_string(index=False))

import pandas as pd
import numpy as np
import pyreadstat
import os

datos_escolaridad_corregidos = []

# Supongamos que path_base ya está definido hacia tus carpetas de empleo
for anio in range(1990, 2025):
    # 1. Obtener nombres de variables del Mapa Maestro
    info_anio = df_mapa[df_mapa['Año'] == anio]

    # Buscamos la variable de NIVEL y la de AÑOS
    try:
        col_niv = info_anio[info_anio['Variable_Original_DTA'].str.contains('nivinst|p10a', na=False)]['Variable_Original_DTA'].iloc[0]
        col_ano = info_anio[info_anio['Variable_Original_DTA'].str.contains('anoinst|p10b', na=False)]['Variable_Original_DTA'].iloc[0]
    except IndexError:
        print(f"⚠️ {anio}: No se encontraron variables en el mapa.")
        continue

    # 2. Definir ruta según tu estructura de carpetas
    sub = "1990-1999" if anio <= 1999 else "2000-2006" if anio <= 2006 else "2007-2017" if anio <= 2017 else "2018-presente/Trimestrales"
    ruta = os.path.join(path_base, sub, f"empleo{anio}.dta")

    if os.path.exists(ruta):
        # Leemos solo lo necesario para ahorrar memoria
        df_t, _ = pyreadstat.read_dta(ruta, usecols=[col_niv, col_ano])

        # FORZAMOS NUMÉRICO: A veces pyreadstat lee como categorías
        df_t[col_niv] = pd.to_numeric(df_t[col_niv], errors='coerce')
        df_t[col_ano] = pd.to_numeric(df_t[col_ano], errors='coerce')

        # 3. Aplicamos la lógica de cálculo (Fórmula simplificada para velocidad)
        def calcular_directo(row, n_col, a_col, a):
            niv = row[n_col]
            extra = row[a_col]
            if pd.isna(niv): return np.nan
            # Limpiar el código 99 o valores absurdos de años extra
            extra = extra if (pd.notna(extra) and extra < 15) else 0

            # Base de años según la época (Ajustado a tu auditoría anterior)
            if a <= 2002:
                mapping = {1:0, 2:0, 3:0, 4:6, 5:12} # 1990-2002
            else:
                mapping = {1:0, 2:0, 3:0, 4:0, 5:0, 6:6, 7:6, 8:12, 9:12, 10:17} # Reforma

            return mapping.get(niv, 0) + extra

        df_t['anios_estudio'] = df_t.apply(lambda x: calcular_directo(x, col_niv, col_ano, anio), axis=1)
        df_t['anio'] = anio

        datos_escolaridad_corregidos.append(df_t[['anio', 'anios_estudio']])
        print(f"✅ {anio} Procesado | Media: {df_t['anios_estudio'].mean():.2f}")
    else:
        print(f"❌ {anio}: Archivo no encontrado en {ruta}")

# Unificar todo
df_edu_final = pd.concat(datos_escolaridad_corregidos, ignore_index=True)

# Estadísticas descriptivas finales
resumen = df_edu_final.groupby('anio')['anios_estudio'].agg(['mean', 'std', 'max', 'count']).round(2)
display(resumen)

import matplotlib.pyplot as plt
import seaborn as sns

# Configuramos el estilo
plt.figure(figsize=(15, 8))
sns.set_context("talk")

# Graficamos la media
plt.plot(resumen.index, resumen['mean'], marker='o', color='#1F618D', linewidth=3, label='Media de Años de Estudio')

# Añadimos áreas de confianza (opcional pero elegante)
plt.fill_between(resumen.index, resumen['mean'] - 0.5, resumen['mean'] + 0.5, color='#AED6F1', alpha=0.3)

# Anotaciones de hitos históricos
plt.axvline(x=2003, color='red', linestyle='--', alpha=0.6)
plt.text(2003.5, 6, 'Reforma Educativa\n(Educación Básica)', color='red', fontsize=12)

plt.axvline(x=2007, color='green', linestyle='--', alpha=0.6)
plt.text(2007.5, 9, 'Cambio de Metodología\n(p10a / p10b)', color='green', fontsize=12)

# Estética
plt.title('Evolución del Capital Humano en Ecuador (1990-2024)', fontsize=20, fontweight='bold')
plt.xlabel('Año', fontsize=14)
plt.ylabel('Promedio de Años de Escolaridad', fontsize=14)
plt.grid(True, which='both', linestyle='--', alpha=0.5)
plt.xticks(resumen.index[::2], rotation=45)
plt.legend()

plt.tight_layout()
plt.show()

"""**Unir bases**"""

import pandas as pd
import os

path_guardado = "/content/drive/MyDrive/Observatorio/Bases_limpias"

# 1. Definimos la lista de archivos a unir
archivos = [
    "Master_Provincia_90_24.dta",
    "Master_Edad_90_24.dta",
    "Master_Educacion_90_24.dta",
    "Master_Sector_Informal_90_24.dta",
    "Master_Afiliacion_Estricta_90_24.dta"
]

print("🧵 Iniciando la costura de bases maestras...")

# 2. Cargamos el primer archivo como base
df_final = pd.read_stata(os.path.join(path_guardado, archivos[0]))
print(f"✅ Base inicial cargada: {archivos[0]} ({df_final.shape[0]:,} registros)")

# 3. Unimos los demás archivos uno por uno
for archivo in archivos[1:]:
    df_temp = pd.read_stata(os.path.join(path_guardado, archivo))

    # Unimos horizontalmente (asumiendo que el orden de filas es idéntico)
    # Si tienen una columna 'id' o similar, se usa: on=['anio', 'id']
    # Si no, concatenamos columnas nuevas descartando las repetidas (como 'anio')
    columnas_nuevas = df_temp.columns.difference(df_final.columns)
    df_final = pd.concat([df_final, df_temp[columnas_nuevas]], axis=1)

    print(f"✅ Integrado: {archivo}. Columnas totales: {df_final.shape[1]}")

# 4. Exportación del "Santo Grial" de tu tesis
ruta_final = os.path.join(path_guardado, "Base_Ecuador_1990_2024.parquet")
# Uso Parquet porque es 10 veces más rápido y ligero que .dta para archivos gigantes
df_final.to_parquet(ruta_final, index=False)

print("-" * 50)
print(f"🏆 ¡LOGRADO! Base única generada en: {ruta_final}")

import pandas as pd

# 1. Cargar la base final (ajusta el nombre si usaste .dta o .parquet)
ruta_base_final = "/content/drive/MyDrive/Observatorio/Bases_limpias/Base_Ecuador_1990_2024.parquet"
df_master = pd.read_parquet(ruta_base_final)

def check_final(df):
    print("📋 INSPECCIÓN TÉCNICA DE LA BASE MAESTRA")
    print("-" * 80)

    # Check 1: ¿Están todas las variables?
    print(f"✅ Variables detectadas: {list(df.columns)}")

    # Check 2: ¿Hay filas vacías?
    nulos = df.isnull().sum().sum()
    print(f"✅ Total de datos nulos en toda la base: {nulos}")

    # Check 3: Resumen por variable clave
    print("\n🧐 MUESTRA DE CONSISTENCIA (Primeros 5 registros):")
    # Correcting the column names to match the actual DataFrame columns
    display(df[['anio', 'provincia_cod', 'edad_num', 'nivel_educativo', 'sector_informal']].head())

    # Check 4: ¿El sector informal tiene datos en todos los años?
    print("\n📉 CONTEO DE REGISTROS POR AÑO (Primeros y últimos):")
    counts = df.groupby('anio').size()
    print(pd.concat([counts.head(3), counts.tail(3)]))

check_final(df_master)